"use client";
import {useEffect,useState} from "react";
import MobileAppShell from "../../../../components/layout/MobileAppShell";
type Provider={id:string;name:string;mode:string;docsUrl?:string;secretKeys:string[];capabilities:string[];automatedKeyCreation:boolean;connected:boolean;status:string;lastError?:string|null};
export default function Page(){
 const [providers,setProviders]=useState<Provider[]>([]),[targets,setTargets]=useState<any>({}),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const r=await fetch("/api/ai/provider-integrations",{cache:"no-store"});const j=await r.json();if(j.success){setProviders(j.data.providers);setTargets(j.data.secretTargets)}};
 useEffect(()=>{void load()},[]);
 const connect=async(id:string)=>{setBusy(id);setMessage("");const r=await fetch(`/api/ai/provider-integrations/${id}/connect`,{method:"POST"});const j=await r.json();if(j.success&&j.data.authorizationUrl)window.location.href=j.data.authorizationUrl;else setMessage(j.data?.message??j.error?.message??"Connection requires provider-specific setup.");setBusy("")};
 const save=async(id:string)=>{const value=window.prompt("Paste the provider credential once. It will be sent directly to the selected secret target and never rendered back.");if(!value)return;const target=window.prompt("Secret target: railway or render","railway")||"railway";setBusy(id);const r=await fetch(`/api/ai/provider-integrations/${id}/credential`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({value,target})});const j=await r.json();setMessage(j.success?`${id} connected and secret synchronized.`:j.error?.message??"Credential sync failed.");setBusy("");void load()};
 return <MobileAppShell theme="dark"><main className="min-h-screen bg-slate-950 px-4 py-8 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs uppercase tracking-[.2em] text-blue-400">AI System / Plugin & Integration</p><h1 className="mt-2 text-3xl font-bold">Provider Integrations</h1><p className="mt-3 text-slate-400">Connect providers and synchronize credentials into platform secrets. Secret values are never stored in the database.</p><div className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm">Railway secret bridge: <b>{targets.railway?"READY":"NOT CONFIGURED"}</b> · Render secret bridge: <b>{targets.render?"READY":"NOT CONFIGURED"}</b></div><section className="mt-6 grid gap-4 md:grid-cols-2">{providers.map(p=><article key={p.id} className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{p.name}</h2><span className={p.connected?"text-emerald-400":"text-amber-400"}>{p.connected?"CONNECTED":p.status}</span></div><p className="mt-2 text-xs text-slate-500">{p.mode} · {p.automatedKeyCreation?"automated provisioning capable":"provider-specific/manual credential flow"}</p><div className="mt-3 flex flex-wrap gap-2">{p.capabilities.map(c=><span key={c} className="rounded-full bg-white/10 px-2 py-1 text-xs">{c}</span>)}</div><div className="mt-5 flex gap-2"><button disabled={busy===p.id} onClick={()=>void connect(p.id)} className="rounded-xl bg-blue-600 px-4 py-2 text-sm">{busy===p.id?"Working…":"Connect"}</button><button disabled={busy===p.id} onClick={()=>void save(p.id)} className="rounded-xl border border-white/10 px-4 py-2 text-sm">Sync credential</button></div>{p.docsUrl&&<a className="mt-3 inline-block text-xs text-blue-300" href={p.docsUrl} target="_blank">Provider setup</a>}{p.lastError&&<p className="mt-3 text-xs text-red-300">{p.lastError}</p>}</article>)}</section>{message&&<p className="mt-6 rounded-xl border border-white/10 p-4 text-sm">{message}</p>}</div></main></MobileAppShell>
}
