"use client";

import MobileAppShell from "../../../../components/layout/MobileAppShell";
import {useEffect,useMemo,useState} from "react";

type Memory={id:string;content:string;namespace:string;createdAt:string;updatedAt:string;metadata?:any};

export default function MemoryPage(){
 const base=(process.env.NEXT_PUBLIC_API_URL??"").replace(/\/$/,"");
 const [items,setItems]=useState<Memory[]>([]),[content,setContent]=useState(""),[namespace,setNamespace]=useState("default"),[query,setQuery]=useState(""),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function load(){const r=await fetch(base+"/api/ai/memories",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d?.error?.message??"Unable to load memories.");setItems(d.data??[])}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
 const visible=useMemo(()=>items.filter(x=>(x.content+" "+x.namespace).toLowerCase().includes(query.toLowerCase())),[items,query]);
 function edit(x:Memory){setEditing(x.id);setContent(x.content);setNamespace(x.namespace);setError("");window.scrollTo({top:0,behavior:"smooth"})}
 function reset(){setEditing(null);setContent("");setNamespace("default")}
 async function save(){if(!content.trim())return;setLoading(true);setError("");try{const url=editing?base+"/api/ai/memories/"+editing:base+"/api/ai/memories";const r=await fetch(url,{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content,namespace})});const d=await r.json();if(!r.ok)throw Error(d?.error?.message??"Unable to save memory.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"Save failed")}finally{setLoading(false)}}
 async function remove(id:string){if(!window.confirm("Delete this memory?"))return;const r=await fetch(base+"/api/ai/memories/"+id,{method:"DELETE"});const d=await r.json();if(!r.ok)throw Error(d?.error?.message??"Unable to delete memory.");if(editing===id)reset();await load()}
 return <MobileAppShell theme="dark"><main className="min-h-screen px-4 py-8 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-400">AI System / Memory</p><h1 className="mt-2 text-3xl font-bold">AI Memory</h1><p className="mt-3 text-slate-400">Persistent context used by AI conversations and the existing agent brain.</p>
 <div className="mt-8 grid gap-5 lg:grid-cols-[380px_1fr]"><section className="rounded-2xl border border-white/10 bg-slate-900/80 p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{editing?"Edit Memory":"Store Memory"}</h2>{editing&&<button onClick={reset} className="text-xs text-slate-400">Cancel</button>}</div><input value={namespace} onChange={e=>setNamespace(e.target.value)} placeholder="Namespace" className="mt-4 w-full rounded-xl bg-black/20 p-3 text-sm ring-1 ring-white/10"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Important information or context..." className="mt-3 min-h-48 w-full rounded-xl bg-black/20 p-3 text-sm leading-6 ring-1 ring-white/10"/><button onClick={()=>void save()} disabled={loading||!content.trim()} className="mt-3 rounded-full bg-white px-5 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">{loading?"Saving…":editing?"Update Memory":"Save Memory"}</button>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}</section>
 <section><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-bold">{visible.length} memories</h2><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search local memories..." className="w-full max-w-sm rounded-xl bg-slate-900 p-3 text-sm ring-1 ring-white/10"/></div><div className="space-y-3">{visible.map(x=><article key={x.id} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-bold uppercase tracking-wider text-blue-300">{x.namespace}</span><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-200">{x.content}</p></div><div className="flex shrink-0 gap-3 text-xs"><button onClick={()=>edit(x)} className="text-slate-300">Edit</button><button onClick={()=>void remove(x.id).catch(e=>setError(e.message))} className="text-red-300">Delete</button></div></div><p className="mt-3 text-[10px] text-slate-500">Updated {new Date(x.updatedAt).toLocaleString()} · {x.metadata?.type??"memory"}</p></article>)}{!visible.length&&<p className="rounded-xl border border-white/10 p-6 text-sm text-slate-500">No memories found.</p>}</div></section></div></div></main></MobileAppShell>
}
