"use client";

import MobileAppShell from "../../../../components/layout/MobileAppShell";
import { useEffect, useMemo, useState } from "react";
type Memory={id:string;content:string;namespace:string;createdAt:string;updatedAt:string;metadata?:any;embedding?:unknown};
async function readJson(r:Response){const text=await r.text();let d:any={};try{d=text?JSON.parse(text):{}}catch{throw Error(`Server returned an invalid response (HTTP ${r.status}).`);}if(!r.ok)throw Error(d?.error?.message??`Request failed (HTTP ${r.status}).`);return d;}
export default function MemoryPage(){
 const base=(process.env.NEXT_PUBLIC_API_URL??"").replace(/\/$/,"");const [items,setItems]=useState<Memory[]>([]),[content,setContent]=useState(""),[namespace,setNamespace]=useState("default"),[query,setQuery]=useState(""),[results,setResults]=useState<Memory[]|null>(null),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(false),[searching,setSearching]=useState(false);
 async function load(){const d=await readJson(await fetch(base+"/api/ai/memories",{cache:"no-store"}));setItems(d.data??[]);}
 useEffect(()=>{void load().catch(e=>setError(e instanceof Error?e.message:"Unable to load memories."));},[]);
 const visible=useMemo(()=>results??items.filter(x=>(x.content+" "+x.namespace).toLowerCase().includes(query.toLowerCase())),[items,query,results]);
 function edit(x:Memory){setResults(null);setEditing(x.id);setContent(x.content);setNamespace(x.namespace);setError("");window.scrollTo({top:0,behavior:"smooth"});}
 function reset(){setEditing(null);setContent("");setNamespace("default");}
 async function save(){if(!content.trim())return;setLoading(true);setError("");try{await readJson(await fetch(editing?base+"/api/ai/memories/"+editing:base+"/api/ai/memories",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content,namespace})}));reset();await load();setResults(null);setQuery("");}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setLoading(false);}}
 async function semanticSearch(){const q=query.trim();if(!q){setResults(null);return;}setSearching(true);setError("");try{const d=await readJson(await fetch(base+"/api/ai/memories/search?q="+encodeURIComponent(q),{cache:"no-store"}));setResults(d.data??[]);}catch(e){setError(e instanceof Error?e.message:"Semantic search failed.");}finally{setSearching(false);}}
 async function remove(id:string){if(!window.confirm("Delete this memory?"))return;try{await readJson(await fetch(base+"/api/ai/memories/"+id,{method:"DELETE"}));if(editing===id)reset();await load();setResults(null);}catch(e){setError(e instanceof Error?e.message:"Unable to delete memory.");}}
 return <MobileAppShell theme="dark"><main className="min-h-screen px-4 py-8 text-white sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-400">AI System / Memory</p><h1 className="mt-2 text-3xl font-bold">AI Memory</h1><p className="mt-3 text-slate-400">Persistent context used by AI conversations and the existing agent brain.</p>
 <div className="mt-8 grid gap-5 lg:grid-cols-[380px_1fr]"><section className="rounded-2xl border border-white/10 bg-slate-900/80 p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{editing?"Edit Memory":"Store Memory"}</h2>{editing&&<button onClick={reset} className="text-xs text-slate-400">Cancel</button>}</div><input value={namespace} onChange={e=>setNamespace(e.target.value)} placeholder="Namespace" className="mt-4 w-full rounded-xl bg-black/20 p-3 text-sm ring-1 ring-white/10"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Important information or context..." className="mt-3 min-h-48 w-full rounded-xl bg-black/20 p-3 text-sm leading-6 ring-1 ring-white/10"/><button onClick={()=>void save()} disabled={loading||!content.trim()} className="mt-3 rounded-full bg-white px-5 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50">{loading?"Saving…":editing?"Update Memory":"Save Memory"}</button>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}</section>
 <section><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">{visible.length} results</h2>{results&&<p className="text-xs text-slate-500">Semantic search results</p>}</div><div className="flex w-full max-w-sm gap-2"><input value={query} onChange={e=>{setQuery(e.target.value);if(!e.target.value)setResults(null)}} onKeyDown={e=>{if(e.key==="Enter")void semanticSearch()}} placeholder="Search or semantic query..." className="min-w-0 flex-1 rounded-xl bg-slate-900 p-3 text-sm ring-1 ring-white/10"/><button onClick={()=>void semanticSearch()} disabled={searching} className="rounded-xl bg-white/10 px-3 text-xs">{searching?"…":"Search"}</button></div></div>
 <div className="space-y-3">{visible.map(x=><article key={x.id} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-bold uppercase tracking-wider text-blue-300">{x.namespace}</span><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-200">{x.content}</p></div><div className="flex shrink-0 gap-3 text-xs"><button onClick={()=>edit(x)} className="text-slate-300">Edit</button><button onClick={()=>void remove(x.id)} className="text-red-300">Delete</button></div></div><p className="mt-3 text-[10px] text-slate-500">Updated {new Date(x.updatedAt).toLocaleString()} · {x.metadata?.type??"memory"}</p></article>)}{!visible.length&&<p className="rounded-xl border border-white/10 p-6 text-sm text-slate-500">No memories found.</p>}</div></section></div></div></main></MobileAppShell>;
}