import { Router } from "express";
import { addKnowledge, chat, createJob, listAgents, getAgent, createAgent, updateAgent, listAgentRuns, listJobs, listKnowledge, orchestrate, runAgentRoute, agentAutomationOverview, createAutomation, updateAutomation, runAutomation, listAutomationRuns, approveAutomationRun, retryAutomationRun, diagnoseAutomation, brainProfile, linkKnowledgeToAgent, linkMemoryToAgent, runAgentChain, controlCenter } from "../controllers/aiController.js";
import { reindexKnowledgeRoute } from "../controllers/aiController.js";
import { listAIProviders, listAIProviderEvents } from "../controllers/aiProviderController.js";
import { controlChat } from "../controllers/aiChatControlController.js";
import { requireAdminAuth } from "../middleware/adminAuth.js";
import { listConversations, getConversation, renameConversation, deleteConversation, listMemories, createMemory, updateMemory, deleteMemory, searchMemories, updateKnowledge, deleteKnowledge, searchKnowledge } from "../controllers/aiContextController.js";
const router=Router();
// All AI routes contain private conversations, memories, agent operations, or provider data.
// Require the server-side admin bearer token consistently; the frontend same-origin proxy supplies it after session validation.
router.use(requireAdminAuth);
router.get("/providers",listAIProviders);
router.get("/providers/events",listAIProviderEvents);
router.post("/providers/reindex-knowledge",reindexKnowledgeRoute);
router.post("/chat",chat);
router.post("/control-chat",controlChat);
router.get("/conversations",listConversations);
router.get("/conversations/:id",getConversation);
router.patch("/conversations/:id",renameConversation);
router.delete("/conversations/:id",deleteConversation);
router.get("/memories/search",searchMemories);
router.get("/memories",listMemories);
router.post("/memories",createMemory);
router.patch("/memories/:id",updateMemory);
router.delete("/memories/:id",deleteMemory);
router.get("/agents",listAgents);
router.post("/agents",createAgent);
router.get("/agents/:id",getAgent);
router.patch("/agents/:id",updateAgent);
router.get("/agents/:id/runs",listAgentRuns);
router.post("/agents/:id/run",runAgentRoute);
router.post("/orchestrate",orchestrate);
router.post("/agent-chain/run",runAgentChain);
router.get("/control-center",controlCenter);
router.get("/knowledge/search",searchKnowledge);
router.get("/knowledge",listKnowledge);
router.post("/knowledge",addKnowledge);
router.patch("/knowledge/:id",updateKnowledge);
router.delete("/knowledge/:id",deleteKnowledge);
router.get("/jobs",listJobs);
router.post("/jobs",createJob);
router.get("/agent-automation",agentAutomationOverview);
router.post("/automations/diagnose",diagnoseAutomation);
router.post("/automations",createAutomation);
router.patch("/automations/:id",updateAutomation);
router.post("/automations/:id/run",runAutomation);
router.get("/automations/:id/runs",listAutomationRuns);
router.post("/automation-runs/:runId/approve",approveAutomationRun);
router.post("/automation-runs/:runId/retry",retryAutomationRun);
router.get("/agents/:agentId/brain",brainProfile);
router.post("/agents/:agentId/brain/knowledge",linkKnowledgeToAgent);
router.post("/agents/:agentId/brain/memory",linkMemoryToAgent);
export default router;