import { Router } from "express";
import { addKnowledge, chat, createJob, listAgents, listJobs, listKnowledge, orchestrate, runAgentRoute, agentAutomationOverview, createAutomation, updateAutomation, runAutomation, listAutomationRuns, brainProfile, linkKnowledgeToAgent, linkMemoryToAgent } from "../controllers/aiController.js";
const router=Router();
router.post("/chat",chat);
router.get("/agents",listAgents);
router.post("/agents/:id/run",runAgentRoute);
router.post("/orchestrate",orchestrate);
router.get("/knowledge",listKnowledge);
router.post("/knowledge",addKnowledge);
router.get("/jobs",listJobs);
router.post("/jobs",createJob);
router.get("/agent-automation",agentAutomationOverview);
router.post("/automations",createAutomation);
router.patch("/automations/:id",updateAutomation);
router.post("/automations/:id/run",runAutomation);
router.get("/automations/:id/runs",listAutomationRuns);
router.get("/agents/:agentId/brain",brainProfile);
router.post("/agents/:agentId/brain/knowledge",linkKnowledgeToAgent);
router.post("/agents/:agentId/brain/memory",linkMemoryToAgent);
export default router;
